stages:
  - update

update_staging:
    stage: update
    before_script:
        - 'which ssh-agent || ( apk update && apk add --no-cache openssh )'
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY_STAGING" | tr -d '\r' > ~/.ssh/id_rsa
        - chmod 700 ~/.ssh/id_rsa
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_rsa
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script:
        - bash ./gitlabpull.sh
    only:
        - master

